# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
  displayName: 'Terraform installer'
- task: TerraformCLI@1
  inputs:
    command: 'init'
    allowTelemetryCollection: true
  displayName: 'terraform init'
- task: TerraformCLI@1
  inputs:
    command: 'validate'
    allowTelemetryCollection: true
  displayName: 'Terraform validate'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'IAC/Templates'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)'

- task: TerraformCLI@1
  inputs:
    command: 'apply'
    allowTelemetryCollection: true
  displayName: 'Terraform apply'